# Generated by Django 2.0 on 2018-02-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20180211_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='email',
            field=models.CharField(blank=True, default='notifymailer@gmail.com', max_length=20),
        ),
        migrations.AlterField(
            model_name='customers',
            name='date',
            field=models.FloatField(blank=True, default=1518389984.6290264, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='added',
            field=models.FloatField(blank=True, default=1518389984.6290264, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.FloatField(blank=True, default=1518389984.6290264, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='joined',
            field=models.IntegerField(blank=True, default=1518389984.6290264),
        ),
    ]
